### ISSUE TITLE
how to run this project?

### ISSUE THREAD

**Issue by joanmj** [hivejs/hive-editor-html-ckeditor#1]
After clone the project and "npm install " to install the dependencies, I use this command:
`node index.js`
but nothing happened, why? how to run it?

**Comment by marcelklehr** [comment]
Have you read the installation instructions in hivejs/docs ? That should clear up a few things ;)

**Comment by marcelklehr** [comment]
You cannot run the code in this repo without installing hive.js and adding this editor as a component.

I think what you probably need is something like [gulf](http://github.com/gulf/gulf) along with [gulf-editor-contenteditable]https://github.com/gulf/gulf-editor-contenteditable).
